"""Pinned, local multilingual embedding support.

The corpus stores passage vectors generated at build time. Query vectors are
generated by the same bundled model at chat time, independently of the LLM
provider. The adapter keeps the optional runtime import lazy so lexical-only
artifacts do not require a model to start.
"""

from collections.abc import Callable, Sequence
from dataclasses import dataclass
from math import sqrt
from pathlib import Path
from typing import Any, Literal

EmbeddingKind = Literal["query", "passage"]


@dataclass(frozen=True)
class EmbeddingModelSpec:
    """Identity and preprocessing contract for one embedding model."""

    model_id: str
    revision: str
    dimensions: int
    model_file: str
    query_prefix: str = "query: "
    passage_prefix: str = "passage: "
    pooling: Literal["mean"] = "mean"


DEFAULT_EMBEDDING_MODEL = EmbeddingModelSpec(
    model_id="intfloat/multilingual-e5-small",
    # This revision contains the optimized ONNX file configured below. Keep
    # the revision and filename together: FastEmbed otherwise reports a vague
    # local-model error when the snapshot predates the exported file.
    revision="4a4cddf9cf6d77a61cc1c73f824ec2127773db85",
    dimensions=384,
    model_file="onnx/model_O4.onnx",
)


def prefixed_texts(
    texts: Sequence[str],
    *,
    kind: EmbeddingKind,
    model_spec: EmbeddingModelSpec = DEFAULT_EMBEDDING_MODEL,
) -> tuple[str, ...]:
    """Apply E5's asymmetric query/passage prefixes to non-empty texts."""
    prefix = model_spec.query_prefix if kind == "query" else model_spec.passage_prefix
    result: list[str] = []
    for text in texts:
        cleaned = " ".join(text.split())
        if not cleaned:
            raise ValueError("embedding text cannot be empty")
        result.append(prefix + cleaned)
    return tuple(result)


class LocalEmbeddingEncoder:
    """Encode short texts with a bundled FastEmbed-compatible model directory."""

    def __init__(
        self,
        model_dir: Path,
        *,
        model_spec: EmbeddingModelSpec = DEFAULT_EMBEDDING_MODEL,
        model_factory: Callable[[Path], Any] | None = None,
    ) -> None:
        self.model_dir = model_dir
        self.model_spec = model_spec
        self._model = (
            model_factory(model_dir) if model_factory is not None else self._load_model(model_dir)
        )

    def encode(self, texts: Sequence[str], *, kind: EmbeddingKind) -> tuple[tuple[float, ...], ...]:
        prepared = prefixed_texts(texts, kind=kind, model_spec=self.model_spec)
        vectors = tuple(self._model.embed(prepared))
        if len(vectors) != len(prepared):
            raise ValueError("embedding backend returned the wrong number of vectors")
        normalized: list[tuple[float, ...]] = []
        for vector in vectors:
            values = tuple(float(value) for value in vector)
            if len(values) != self.model_spec.dimensions:
                raise ValueError(
                    f"embedding backend returned {len(values)} dimensions; "
                    f"expected {self.model_spec.dimensions} dimensions"
                )
            norm = sqrt(sum(value * value for value in values))
            if norm == 0:
                raise ValueError("embedding backend returned a zero vector")
            normalized.append(tuple(value / norm for value in values))
        return tuple(normalized)

    @staticmethod
    def _load_model(model_dir: Path) -> Any:
        try:
            import importlib

            fastembed = importlib.import_module("fastembed")
            model_description = importlib.import_module("fastembed.common.model_description")
            TextEmbedding = fastembed.TextEmbedding
            ModelSource = model_description.ModelSource
            PoolingType = model_description.PoolingType
        except ImportError as error:  # pragma: no cover - exercised without optional dependency
            raise RuntimeError(
                "semantic search requires the fastembed dependency; install the semantic extra"
            ) from error

        model_spec = DEFAULT_EMBEDDING_MODEL
        model_path = model_dir / model_spec.model_file
        if not model_path.is_file():
            raise ValueError(
                "semantic model snapshot is missing the configured model file: "
                f"{model_spec.model_file}"
            )

        TextEmbedding.add_custom_model(
            model=model_spec.model_id,
            pooling=PoolingType.MEAN,
            normalization=True,
            sources=ModelSource(hf=model_spec.model_id),
            dim=model_spec.dimensions,
            model_file=model_spec.model_file,
        )
        return TextEmbedding(
            model_name=model_spec.model_id,
            specific_model_path=str(model_dir),
            local_files_only=True,
        )


__all__ = [
    "DEFAULT_EMBEDDING_MODEL",
    "EmbeddingModelSpec",
    "LocalEmbeddingEncoder",
    "prefixed_texts",
]
