"""Pinned, local multilingual embedding support.

The corpus stores passage vectors generated at build time. Query vectors are
generated by the same bundled model at chat time, independently of the LLM
provider. The adapter keeps the optional runtime import lazy so lexical-only
artifacts do not require a model to start.
"""

from collections.abc import Callable, Sequence
from dataclasses import dataclass
from hashlib import sha256
from math import isfinite, sqrt
from pathlib import Path
from threading import Lock
from typing import Any, Literal

EmbeddingKind = Literal["query", "passage"]
_REGISTRATION_LOCK = Lock()
_REGISTERED_MODELS: dict[tuple[object, ...], str] = {}


@dataclass(frozen=True)
class EmbeddingModelSpec:
    """Identity and preprocessing contract for one embedding model."""

    model_id: str
    revision: str
    dimensions: int
    model_file: str
    query_prefix: str = "query: "
    passage_prefix: str = "passage: "
    pooling: Literal["mean"] = "mean"


def normalize_embedding(vector: Sequence[float], *, dimensions: int) -> tuple[float, ...]:
    """Validate and L2-normalize one embedding for cosine similarity."""
    values = tuple(float(value) for value in vector)
    if len(values) != dimensions:
        raise ValueError(
            f"embedding backend returned {len(values)} dimensions; expected {dimensions} dimensions"
        )
    if not all(isfinite(value) for value in values):
        raise ValueError("embedding backend returned a non-finite value")
    norm = sqrt(sum(value * value for value in values))
    if norm == 0:
        raise ValueError("embedding backend returned a zero vector")
    return tuple(value / norm for value in values)


def cosine_similarity(left: Sequence[float], right: Sequence[float]) -> float:
    """Return cosine similarity for two already validated vectors."""
    if len(left) != len(right):
        raise ValueError("cosine vectors must have matching dimensions")
    return sum(
        left_value * right_value for left_value, right_value in zip(left, right, strict=True)
    )


def model_snapshot_path(model_dir: Path, model_spec: EmbeddingModelSpec) -> Path:
    """Resolve a model file while keeping it inside its supplied snapshot."""
    relative = Path(model_spec.model_file)
    if relative.is_absolute() or not relative.parts or ".." in relative.parts:
        raise ValueError(f"semantic model file must be a relative snapshot path: {relative}")
    path = model_dir / relative
    if not path.is_file():
        raise ValueError(
            f"semantic model snapshot is missing the configured model file: {model_spec.model_file}"
        )
    return path


DEFAULT_EMBEDDING_MODEL = EmbeddingModelSpec(
    model_id="intfloat/multilingual-e5-small",
    # This revision contains the optimized ONNX file configured below. Keep
    # the revision and filename together: FastEmbed otherwise reports a vague
    # local-model error when the snapshot predates the exported file.
    revision="4a4cddf9cf6d77a61cc1c73f824ec2127773db85",
    dimensions=384,
    model_file="onnx/model_O4.onnx",
)


def prefixed_texts(
    texts: Sequence[str],
    *,
    kind: EmbeddingKind,
    model_spec: EmbeddingModelSpec = DEFAULT_EMBEDDING_MODEL,
) -> tuple[str, ...]:
    """Apply E5's asymmetric query/passage prefixes to non-empty texts."""
    prefix = model_spec.query_prefix if kind == "query" else model_spec.passage_prefix
    result: list[str] = []
    for text in texts:
        cleaned = " ".join(text.split())
        if not cleaned:
            raise ValueError("embedding text cannot be empty")
        result.append(prefix + cleaned)
    return tuple(result)


class LocalEmbeddingEncoder:
    """Encode short texts with a bundled FastEmbed-compatible model directory."""

    def __init__(
        self,
        model_dir: Path,
        *,
        model_spec: EmbeddingModelSpec = DEFAULT_EMBEDDING_MODEL,
        model_factory: Callable[[Path], Any] | None = None,
    ) -> None:
        self.model_dir = model_dir
        self.model_spec = model_spec
        self._model = (
            model_factory(model_dir)
            if model_factory is not None
            else self._load_model(model_dir, model_spec)
        )

    def encode(self, texts: Sequence[str], *, kind: EmbeddingKind) -> tuple[tuple[float, ...], ...]:
        prepared = prefixed_texts(texts, kind=kind, model_spec=self.model_spec)
        vectors = tuple(self._model.embed(prepared))
        if len(vectors) != len(prepared):
            raise ValueError("embedding backend returned the wrong number of vectors")
        return tuple(
            normalize_embedding(vector, dimensions=self.model_spec.dimensions) for vector in vectors
        )

    @staticmethod
    def _load_model(model_dir: Path, model_spec: EmbeddingModelSpec) -> Any:
        try:
            import importlib

            fastembed = importlib.import_module("fastembed")
            model_description = importlib.import_module("fastembed.common.model_description")
            TextEmbedding = fastembed.TextEmbedding
            ModelSource = model_description.ModelSource
            PoolingType = model_description.PoolingType
        except ImportError as error:  # pragma: no cover - exercised without optional dependency
            raise RuntimeError(
                "semantic search requires the fastembed dependency; install the semantic extra"
            ) from error

        model_snapshot_path(model_dir, model_spec)

        registration_key = (
            model_spec.model_id,
            model_spec.revision,
            model_spec.dimensions,
            model_spec.model_file,
            model_spec.query_prefix,
            model_spec.passage_prefix,
            model_spec.pooling,
        )
        with _REGISTRATION_LOCK:
            model_name = _REGISTERED_MODELS.get(registration_key)
            if model_name is None:
                digest = sha256(repr(registration_key).encode("utf-8")).hexdigest()[:16]
                model_name = f"papyrus-chat-{digest}"
                TextEmbedding.add_custom_model(
                    model=model_name,
                    pooling=PoolingType.MEAN,
                    normalization=True,
                    sources=ModelSource(hf=model_spec.model_id),
                    dim=model_spec.dimensions,
                    model_file=model_spec.model_file,
                )
                _REGISTERED_MODELS[registration_key] = model_name
        return TextEmbedding(
            model_name=model_name,
            specific_model_path=str(model_dir),
            local_files_only=True,
        )


__all__ = [
    "DEFAULT_EMBEDDING_MODEL",
    "EmbeddingModelSpec",
    "LocalEmbeddingEncoder",
    "cosine_similarity",
    "model_snapshot_path",
    "normalize_embedding",
    "prefixed_texts",
]
